// _MainMenu_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, September 6, 2005 18:18:38 US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MainMenu_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    Controller _controller0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0, _nsImageView1, _nsImageView2;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2, _nsMatrix3, _nsMatrix4, _nsMatrix5;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5;
    javax.swing.JButton _jButton0, _jButton1, _jButton10, _jButton11, _jButton12, _jButton13, _jButton14, _jButton15, _jButton16, _jButton17, _jButton18, _jButton19, _jButton2, _jButton20, _jButton21, _jButton22, _jButton23, _jButton24, _jButton25, _jButton26, _jButton27, _jButton28, _jButton29, _jButton3, _jButton30, _jButton31, _jButton32, _jButton33, _jButton34, _jButton35, _jButton36, _jButton37, _jButton38, _jButton39, _jButton4, _jButton40, _jButton41, _jButton42, _jButton43, _jButton44, _jButton45, _jButton46, _jButton47, _jButton48, _jButton49, _jButton5, _jButton50, _jButton51, _jButton52, _jButton53, _jButton54, _jButton55, _jButton56, _jButton57, _jButton58, _jButton59, _jButton6, _jButton60, _jButton61, _jButton62, _jButton63, _jButton64, _jButton65, _jButton66, _jButton67, _jButton7, _jButton8, _jButton9, _nsButton0, _nsButton1;
    javax.swing.JComboBox _popup0, _popup1, _popup2;
    javax.swing.JPanel _nsView0;

    public _MainMenu_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2211");
        _nsMatrix5 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 9, 4), "");
        _nsMatrix4 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(6, 2, 9, 4), "");
        _nsMatrix3 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(6, 1, 9, 4), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsImageView2 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsImageView1 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("ASCII Table"), "NSButton21");
        _popup2 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton12111");
        _jButton67 = (javax.swing.JButton)_registered(new javax.swing.JButton("AC"), "");
        _jButton66 = (javax.swing.JButton)_registered(new javax.swing.JButton("C"), "");
        _jButton65 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton64 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton63 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton62 = (javax.swing.JButton)_registered(new javax.swing.JButton("MR"), "");
        _jButton61 = (javax.swing.JButton)_registered(new javax.swing.JButton("M+"), "");
        _jButton60 = (javax.swing.JButton)_registered(new javax.swing.JButton("MC"), "NSButton21");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("="), "");
        _jButton59 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton58 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton57 = (javax.swing.JButton)_registered(new javax.swing.JButton("-1"), "");
        _jButton56 = (javax.swing.JButton)_registered(new javax.swing.JButton("+1"), "");
        _jButton55 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton54 = (javax.swing.JButton)_registered(new javax.swing.JButton("%"), "");
        _jButton53 = (javax.swing.JButton)_registered(new javax.swing.JButton("x!"), "");
        _jButton52 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u00b1"), "");
        _jButton51 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "");
        _jButton50 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "");
        _jButton49 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u00f7"), "");
        _jButton48 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton47 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u00bb"), "");
        _jButton46 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u00ab"), "");
        _jButton45 = (javax.swing.JButton)_registered(new javax.swing.JButton("~"), "");
        _jButton44 = (javax.swing.JButton)_registered(new javax.swing.JButton("xor"), "");
        _jButton43 = (javax.swing.JButton)_registered(new javax.swing.JButton("or"), "");
        _jButton42 = (javax.swing.JButton)_registered(new javax.swing.JButton("and"), "NSButton2111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.bitPad")) != null)) {
            _nsMatrix2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix2");
        } else {
            _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(6, 1, 9, 4), "");
        }

        _jButton41 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u03c0"), "");
        _jButton40 = (javax.swing.JButton)_registered(new javax.swing.JButton(" e "), "");
        _jButton39 = (javax.swing.JButton)_registered(new javax.swing.JButton("1/x"), "");
        _jButton38 = (javax.swing.JButton)_registered(new javax.swing.JButton("logXbaseY"), "");
        _jButton37 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton36 = (javax.swing.JButton)_registered(new javax.swing.JButton("ln"), "");
        _jButton35 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton34 = (javax.swing.JButton)_registered(new javax.swing.JButton("log"), "");
        _jButton33 = (javax.swing.JButton)_registered(new javax.swing.JButton("trunc"), "");
        _jButton32 = (javax.swing.JButton)_registered(new javax.swing.JButton("round"), "");
        _jButton31 = (javax.swing.JButton)_registered(new javax.swing.JButton("ceil"), "");
        _jButton30 = (javax.swing.JButton)_registered(new javax.swing.JButton("floor"), "");
        _jButton29 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton28 = (javax.swing.JButton)_registered(new javax.swing.JButton("tanh"), "");
        _jButton27 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton26 = (javax.swing.JButton)_registered(new javax.swing.JButton("tan"), "");
        _jButton25 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton24 = (javax.swing.JButton)_registered(new javax.swing.JButton("cosh"), "");
        _jButton23 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton22 = (javax.swing.JButton)_registered(new javax.swing.JButton("cos"), "");
        _jButton21 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton20 = (javax.swing.JButton)_registered(new javax.swing.JButton("sinh"), "");
        _jButton19 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton18 = (javax.swing.JButton)_registered(new javax.swing.JButton("sin"), "NSButton2111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.mathPad")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(6, 4, 9, 4), "");
        }

        _jButton17 = (javax.swing.JButton)_registered(new javax.swing.JButton("EE"), "");
        _jButton16 = (javax.swing.JButton)_registered(new javax.swing.JButton("0"), "");
        _jButton15 = (javax.swing.JButton)_registered(new javax.swing.JButton("."), "");
        _jButton14 = (javax.swing.JButton)_registered(new javax.swing.JButton("3"), "");
        _jButton13 = (javax.swing.JButton)_registered(new javax.swing.JButton("2"), "");
        _jButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton("1"), "");
        _jButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton("6"), "");
        _jButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("5"), "");
        _jButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("4"), "");
        _jButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("9"), "");
        _jButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("8"), "");
        _jButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("7"), "");
        _jButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("C"), "");
        _jButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("B"), "");
        _jButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("A"), "");
        _jButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("F"), "");
        _jButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("E"), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("D"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.keyPad")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(6, 3, 9, 4), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.sizePopup")) != null)) {
            _popup1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup1");
        } else {
            _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.basePopup")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.mOut")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.xOut")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate")) != null)) {
            _controller0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (Controller)replacement;
            _replacedObjects.setObjectForKey(replacement, "_controller0");
        } else {
            _controller0 = (Controller)_registered(new Controller(), "Controller");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.yOut")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "unhideAllApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hide", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hideOtherApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "orderFrontStandardAboutPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "terminate", ), ""));

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_owner(), _controller0, "delegate");
        }

        _popup2.setModel(new javax.swing.DefaultComboBoxModel());
        _popup2.addItem("Degrees");
        _popup2.addItem("Radians");

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _popup1.setModel(new javax.swing.DefaultComboBoxModel());
            _popup1.addItem("Float");
            _popup1.addItem("UInt64");
            _popup1.addItem("Int64");
            _popup1.addItem("UInt32");
            _popup1.addItem("Int32");
            _popup1.addItem("UInt16");
            _popup1.addItem("Int16");
            _popup1.addItem("UInt8");
            _popup1.addItem("Int8");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Decimal");
            _popup0.addItem("Hexadecimal");
            _popup0.addItem("Octal");
            _popup0.addItem("Binary");
            _popup0.addItem("ASCII");
        }
    }

    protected void _init() {
        super._init();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "print", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "runPageLayout", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "delete", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "cut", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "showHelp", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "arrangeInFront", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "paste", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "clearRecentDocuments", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "copy", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "toggleContinuousSpellChecking", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "selectAll", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "checkSpelling", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performMiniaturize", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "redo", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "showGuessPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "undo", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performClose", ), ""));
        _setFontForComponent(_nsTextField5, "Optima", 18, Font.PLAIN + Font.ITALIC + Font.BOLD);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("GeekCalc\n");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _jButton66.setSize(40, 27);
        _jButton66.setLocation(0, 0);
        _nsMatrix5.add(_jButton66);
        _jButton67.setSize(40, 27);
        _jButton67.setLocation(0, 26);
        _nsMatrix5.add(_jButton67);
        _jButton48.setSize(45, 27);
        _jButton48.setLocation(0, 0);
        _nsMatrix4.add(_jButton48);
        _jButton49.setSize(45, 27);
        _jButton49.setLocation(45, 0);
        _nsMatrix4.add(_jButton49);
        _jButton50.setSize(45, 27);
        _jButton50.setLocation(0, 26);
        _nsMatrix4.add(_jButton50);
        _jButton51.setSize(45, 27);
        _jButton51.setLocation(45, 26);
        _nsMatrix4.add(_jButton51);
        _jButton52.setSize(45, 27);
        _jButton52.setLocation(0, 52);
        _nsMatrix4.add(_jButton52);
        _jButton53.setSize(45, 27);
        _jButton53.setLocation(45, 52);
        _nsMatrix4.add(_jButton53);
        _jButton54.setSize(45, 27);
        _jButton54.setLocation(0, 78);
        _nsMatrix4.add(_jButton54);
        _jButton55.setSize(45, 27);
        _jButton55.setLocation(45, 78);
        _nsMatrix4.add(_jButton55);
        _jButton56.setSize(45, 27);
        _jButton56.setLocation(0, 104);
        _nsMatrix4.add(_jButton56);
        _jButton57.setSize(45, 27);
        _jButton57.setLocation(45, 104);
        _nsMatrix4.add(_jButton57);
        _jButton58.setSize(45, 27);
        _jButton58.setLocation(0, 130);
        _nsMatrix4.add(_jButton58);
        _jButton59.setSize(45, 27);
        _jButton59.setLocation(45, 130);
        _nsMatrix4.add(_jButton59);
        _jButton60.setSize(51, 27);
        _jButton60.setLocation(0, 0);
        _nsMatrix3.add(_jButton60);
        _jButton61.setSize(51, 27);
        _jButton61.setLocation(0, 26);
        _nsMatrix3.add(_jButton61);
        _jButton62.setSize(51, 27);
        _jButton62.setLocation(0, 52);
        _nsMatrix3.add(_jButton62);
        _jButton63.setSize(51, 27);
        _jButton63.setLocation(0, 78);
        _nsMatrix3.add(_jButton63);
        _jButton64.setSize(51, 27);
        _jButton64.setLocation(0, 104);
        _nsMatrix3.add(_jButton64);
        _jButton65.setSize(51, 27);
        _jButton65.setLocation(0, 130);
        _nsMatrix3.add(_jButton65);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("M");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Y");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _connect(_eoFrame0, _controller0, "delegate");
        _connect(_eoFrame0, _controller0, "controller");
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "showAsciiTable", _nsButton1), ""));
        _setFontForComponent(_popup2, "Lucida Grande", 13, Font.PLAIN);
        _popup2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "setAngleType", _popup2), ""));
        _setFontForComponent(_jButton67, "Lucida Grande", 13, Font.PLAIN);
        _jButton67.setMargin(new Insets(0, 2, 0, 2));
        _jButton67.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "clearAll", _jButton67), ""));
        _connect(_eoFrame0, _jButton66, "clearKey");
        _setFontForComponent(_jButton66, "Lucida Grande", 13, Font.PLAIN);
        _jButton66.setMargin(new Insets(0, 2, 0, 2));
        _jButton66.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "clear", _jButton66), ""));
        _setFontForComponent(_jButton65, "Lucida Grande", 11, Font.PLAIN);
        _jButton65.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton64, "Lucida Grande", 11, Font.PLAIN);
        _jButton64.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton63, "Lucida Grande", 11, Font.PLAIN);
        _jButton63.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton62, "Lucida Grande", 11, Font.PLAIN);
        _jButton62.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton61, "Lucida Grande", 11, Font.PLAIN);
        _jButton61.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton60, "Lucida Grande", 11, Font.PLAIN);
        _jButton60.setMargin(new Insets(0, 2, 0, 2));
        _jButton60.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton60), ""));
        _jButton61.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton61), ""));
        _jButton62.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton62), ""));
        _jButton63.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton63), ""));
        _jButton64.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton64), ""));
        _jButton65.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton65), ""));
        _setFontForComponent(_nsButton0, "Lucida Grande", 18, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _nsButton0), ""));
        _setFontForComponent(_jButton59, "Lucida Grande", 11, Font.PLAIN);
        _jButton59.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton58, "Lucida Grande", 11, Font.PLAIN);
        _jButton58.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton57, "Lucida Grande", 11, Font.PLAIN);
        _jButton57.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton56, "Lucida Grande", 11, Font.PLAIN);
        _jButton56.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton55, "Lucida Grande", 11, Font.PLAIN);
        _jButton55.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton54, "Lucida Grande", 13, Font.PLAIN);
        _jButton54.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton53, "Lucida Grande", 11, Font.PLAIN);
        _jButton53.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton52, "Lucida Grande", 13, Font.PLAIN);
        _jButton52.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton51, "Lucida Grande", 13, Font.PLAIN);
        _jButton51.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton50, "Lucida Grande", 13, Font.PLAIN);
        _jButton50.setMargin(new Insets(0, 2, 0, 2));
        _connect(_eoFrame0, _jButton49, "divideKey");
        _setFontForComponent(_jButton49, "Lucida Grande", 13, Font.PLAIN);
        _jButton49.setMargin(new Insets(0, 2, 0, 2));
        _connect(_eoFrame0, _jButton48, "multiplyKey");
        _setFontForComponent(_jButton48, "Lucida Grande", 13, Font.PLAIN);
        _jButton48.setMargin(new Insets(0, 2, 0, 2));
        _jButton48.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton48), ""));
        _jButton49.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton49), ""));
        _jButton50.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton50), ""));
        _jButton51.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton51), ""));
        _jButton52.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton52), ""));
        _jButton53.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton53), ""));
        _jButton54.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton54), ""));
        _jButton55.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton55), ""));
        _jButton56.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton56), ""));
        _jButton57.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton57), ""));
        _jButton58.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton58), ""));
        _jButton59.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton59), ""));
        _jButton42.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton42), ""));
        _jButton43.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton43), ""));
        _jButton44.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton44), ""));
        _jButton45.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton45), ""));
        _jButton46.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton46), ""));
        _jButton47.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton47), ""));
        _setFontForComponent(_jButton47, "Lucida Grande", 13, Font.PLAIN);
        _jButton47.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton46, "Lucida Grande", 11, Font.PLAIN);
        _jButton46.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton45, "Lucida Grande", 13, Font.PLAIN);
        _jButton45.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton44, "Lucida Grande", 11, Font.PLAIN);
        _jButton44.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton43, "Lucida Grande", 11, Font.PLAIN);
        _jButton43.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton42, "Lucida Grande", 11, Font.PLAIN);
        _jButton42.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _jButton42.setSize(45, 27);
            _jButton42.setLocation(0, 0);
            _nsMatrix2.add(_jButton42);
            _jButton43.setSize(45, 27);
            _jButton43.setLocation(0, 26);
            _nsMatrix2.add(_jButton43);
            _jButton44.setSize(45, 27);
            _jButton44.setLocation(0, 52);
            _nsMatrix2.add(_jButton44);
            _jButton45.setSize(45, 27);
            _jButton45.setLocation(0, 78);
            _nsMatrix2.add(_jButton45);
            _jButton46.setSize(45, 27);
            _jButton46.setLocation(0, 104);
            _nsMatrix2.add(_jButton46);
            _jButton47.setSize(45, 27);
            _jButton47.setLocation(0, 130);
            _nsMatrix2.add(_jButton47);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsMatrix2, "bitPad");
        }

        _jButton18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton18), ""));
        _jButton19.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton19), ""));
        _jButton20.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton20), ""));
        _jButton21.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton21), ""));
        _jButton22.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton22), ""));
        _jButton23.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton23), ""));
        _jButton24.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton24), ""));
        _jButton25.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton25), ""));
        _jButton26.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton26), ""));
        _jButton27.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton27), ""));
        _jButton28.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton28), ""));
        _jButton29.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton29), ""));
        _jButton30.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton30), ""));
        _jButton31.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton31), ""));
        _jButton32.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton32), ""));
        _jButton33.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton33), ""));
        _jButton34.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton34), ""));
        _jButton35.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton35), ""));
        _jButton36.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton36), ""));
        _jButton37.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton37), ""));
        _jButton38.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton38), ""));
        _jButton39.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton39), ""));
        _jButton40.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton40), ""));
        _jButton41.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "doOp", _jButton41), ""));
        _setFontForComponent(_jButton41, "Lucida Grande", 11, Font.PLAIN);
        _jButton41.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton40, "Lucida Grande", 11, Font.PLAIN);
        _jButton40.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton39, "Lucida Grande", 11, Font.PLAIN);
        _jButton39.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton38, "Lucida Grande", 11, Font.PLAIN);
        _jButton38.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton37, "Lucida Grande", 11, Font.PLAIN);
        _jButton37.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton36, "Lucida Grande", 11, Font.PLAIN);
        _jButton36.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton35, "Lucida Grande", 11, Font.PLAIN);
        _jButton35.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton34, "Lucida Grande", 11, Font.PLAIN);
        _jButton34.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton33, "Lucida Grande", 11, Font.PLAIN);
        _jButton33.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton32, "Lucida Grande", 11, Font.PLAIN);
        _jButton32.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton31, "Lucida Grande", 11, Font.PLAIN);
        _jButton31.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton30, "Lucida Grande", 11, Font.PLAIN);
        _jButton30.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton29, "Lucida Grande", 11, Font.PLAIN);
        _jButton29.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton28, "Lucida Grande", 11, Font.PLAIN);
        _jButton28.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton27, "Lucida Grande", 11, Font.PLAIN);
        _jButton27.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton26, "Lucida Grande", 11, Font.PLAIN);
        _jButton26.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton25, "Lucida Grande", 11, Font.PLAIN);
        _jButton25.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton24, "Lucida Grande", 11, Font.PLAIN);
        _jButton24.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton23, "Lucida Grande", 11, Font.PLAIN);
        _jButton23.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton22, "Lucida Grande", 11, Font.PLAIN);
        _jButton22.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton21, "Lucida Grande", 11, Font.PLAIN);
        _jButton21.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton20, "Lucida Grande", 11, Font.PLAIN);
        _jButton20.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton19, "Lucida Grande", 11, Font.PLAIN);
        _jButton19.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton18, "Lucida Grande", 11, Font.PLAIN);
        _jButton18.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jButton18.setSize(56, 27);
            _jButton18.setLocation(0, 0);
            _nsMatrix1.add(_jButton18);
            _jButton19.setSize(56, 27);
            _jButton19.setLocation(56, 0);
            _nsMatrix1.add(_jButton19);
            _jButton20.setSize(56, 27);
            _jButton20.setLocation(112, 0);
            _nsMatrix1.add(_jButton20);
            _jButton21.setSize(56, 27);
            _jButton21.setLocation(168, 0);
            _nsMatrix1.add(_jButton21);
            _jButton22.setSize(56, 27);
            _jButton22.setLocation(0, 26);
            _nsMatrix1.add(_jButton22);
            _jButton23.setSize(56, 27);
            _jButton23.setLocation(56, 26);
            _nsMatrix1.add(_jButton23);
            _jButton24.setSize(56, 27);
            _jButton24.setLocation(112, 26);
            _nsMatrix1.add(_jButton24);
            _jButton25.setSize(56, 27);
            _jButton25.setLocation(168, 26);
            _nsMatrix1.add(_jButton25);
            _jButton26.setSize(56, 27);
            _jButton26.setLocation(0, 52);
            _nsMatrix1.add(_jButton26);
            _jButton27.setSize(56, 27);
            _jButton27.setLocation(56, 52);
            _nsMatrix1.add(_jButton27);
            _jButton28.setSize(56, 27);
            _jButton28.setLocation(112, 52);
            _nsMatrix1.add(_jButton28);
            _jButton29.setSize(56, 27);
            _jButton29.setLocation(168, 52);
            _nsMatrix1.add(_jButton29);
            _jButton30.setSize(56, 27);
            _jButton30.setLocation(0, 78);
            _nsMatrix1.add(_jButton30);
            _jButton31.setSize(56, 27);
            _jButton31.setLocation(56, 78);
            _nsMatrix1.add(_jButton31);
            _jButton32.setSize(56, 27);
            _jButton32.setLocation(112, 78);
            _nsMatrix1.add(_jButton32);
            _jButton33.setSize(56, 27);
            _jButton33.setLocation(168, 78);
            _nsMatrix1.add(_jButton33);
            _jButton34.setSize(56, 27);
            _jButton34.setLocation(0, 104);
            _nsMatrix1.add(_jButton34);
            _jButton35.setSize(56, 27);
            _jButton35.setLocation(56, 104);
            _nsMatrix1.add(_jButton35);
            _jButton36.setSize(56, 27);
            _jButton36.setLocation(112, 104);
            _nsMatrix1.add(_jButton36);
            _jButton37.setSize(56, 27);
            _jButton37.setLocation(168, 104);
            _nsMatrix1.add(_jButton37);
            _jButton38.setSize(56, 27);
            _jButton38.setLocation(0, 130);
            _nsMatrix1.add(_jButton38);
            _jButton39.setSize(56, 27);
            _jButton39.setLocation(56, 130);
            _nsMatrix1.add(_jButton39);
            _jButton40.setSize(56, 27);
            _jButton40.setLocation(112, 130);
            _nsMatrix1.add(_jButton40);
            _jButton41.setSize(56, 27);
            _jButton41.setLocation(168, 130);
            _nsMatrix1.add(_jButton41);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsMatrix1, "mathPad");
        }

        _jButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton0), ""));
        _jButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton1), ""));
        _jButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton2), ""));
        _jButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton3), ""));
        _jButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton4), ""));
        _jButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton5), ""));
        _jButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton6), ""));
        _jButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton7), ""));
        _jButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton8), ""));
        _jButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton9), ""));
        _jButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton10), ""));
        _jButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton11), ""));
        _jButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton12), ""));
        _jButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton13), ""));
        _jButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton14), ""));
        _jButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton15), ""));
        _jButton16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton16), ""));
        _jButton17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "enterDigit", _jButton17), ""));
        _connect(_eoFrame0, _jButton17, "eeKey");
        _setFontForComponent(_jButton17, "Lucida Grande", 13, Font.PLAIN);
        _jButton17.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton16, "Lucida Grande", 13, Font.PLAIN);
        _jButton16.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton15, "Lucida Grande", 13, Font.PLAIN);
        _jButton15.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton14, "Lucida Grande", 13, Font.PLAIN);
        _jButton14.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton13, "Lucida Grande", 13, Font.PLAIN);
        _jButton13.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton12, "Lucida Grande", 13, Font.PLAIN);
        _jButton12.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton11, "Lucida Grande", 13, Font.PLAIN);
        _jButton11.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton10, "Lucida Grande", 13, Font.PLAIN);
        _jButton10.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton9, "Lucida Grande", 13, Font.PLAIN);
        _jButton9.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton8, "Lucida Grande", 13, Font.PLAIN);
        _jButton8.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton7, "Lucida Grande", 13, Font.PLAIN);
        _jButton7.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton6, "Lucida Grande", 13, Font.PLAIN);
        _jButton6.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton5, "Lucida Grande", 13, Font.PLAIN);
        _jButton5.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton4, "Lucida Grande", 13, Font.PLAIN);
        _jButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton3, "Lucida Grande", 13, Font.PLAIN);
        _jButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton2, "Lucida Grande", 13, Font.PLAIN);
        _jButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton1, "Lucida Grande", 13, Font.PLAIN);
        _jButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton0, "Lucida Grande", 13, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jButton0.setSize(40, 27);
            _jButton0.setLocation(0, 0);
            _nsMatrix0.add(_jButton0);
            _jButton1.setSize(40, 27);
            _jButton1.setLocation(40, 0);
            _nsMatrix0.add(_jButton1);
            _jButton2.setSize(40, 27);
            _jButton2.setLocation(80, 0);
            _nsMatrix0.add(_jButton2);
            _jButton3.setSize(40, 27);
            _jButton3.setLocation(0, 26);
            _nsMatrix0.add(_jButton3);
            _jButton4.setSize(40, 27);
            _jButton4.setLocation(40, 26);
            _nsMatrix0.add(_jButton4);
            _jButton5.setSize(40, 27);
            _jButton5.setLocation(80, 26);
            _nsMatrix0.add(_jButton5);
            _jButton6.setSize(40, 27);
            _jButton6.setLocation(0, 52);
            _nsMatrix0.add(_jButton6);
            _jButton7.setSize(40, 27);
            _jButton7.setLocation(40, 52);
            _nsMatrix0.add(_jButton7);
            _jButton8.setSize(40, 27);
            _jButton8.setLocation(80, 52);
            _nsMatrix0.add(_jButton8);
            _jButton9.setSize(40, 27);
            _jButton9.setLocation(0, 78);
            _nsMatrix0.add(_jButton9);
            _jButton10.setSize(40, 27);
            _jButton10.setLocation(40, 78);
            _nsMatrix0.add(_jButton10);
            _jButton11.setSize(40, 27);
            _jButton11.setLocation(80, 78);
            _nsMatrix0.add(_jButton11);
            _jButton12.setSize(40, 27);
            _jButton12.setLocation(0, 104);
            _nsMatrix0.add(_jButton12);
            _jButton13.setSize(40, 27);
            _jButton13.setLocation(40, 104);
            _nsMatrix0.add(_jButton13);
            _jButton14.setSize(40, 27);
            _jButton14.setLocation(80, 104);
            _nsMatrix0.add(_jButton14);
            _jButton15.setSize(40, 27);
            _jButton15.setLocation(0, 130);
            _nsMatrix0.add(_jButton15);
            _jButton16.setSize(40, 27);
            _jButton16.setLocation(40, 130);
            _nsMatrix0.add(_jButton16);
            _jButton17.setSize(40, 27);
            _jButton17.setLocation(80, 130);
            _nsMatrix0.add(_jButton17);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsMatrix0, "keyPad");
        }

        _popup1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "setNumSize", _popup1), ""));

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _setFontForComponent(_popup1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _popup1, "sizePopup");
        }

        _popup0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_controller0, "setBase", _popup0), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _popup0, "basePopup");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsTextField2, "mOut");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Courier", 36, Font.PLAIN);
            _nsTextField1.setEditable(false);
            _nsTextField1.setOpaque(false);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
            _nsTextField1.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsTextField1, "xOut");
        }

        if (_replacedObjects.objectForKey("_controller0") == null) {
            _connect(_controller0, _nsTextField0, "yOut");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsImageView0.setSize(290, 15);
        _nsImageView0.setLocation(13, 32);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView0);
        _nsTextField0.setSize(288, 14);
        _nsTextField0.setLocation(15, 33);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsImageView1.setSize(290, 15);
        _nsImageView1.setLocation(309, 32);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView1);
        _nsTextField2.setSize(290, 14);
        _nsTextField2.setLocation(309, 33);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsImageView2.setSize(586, 35);
        _nsImageView2.setLocation(13, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView2);
        _nsTextField1.setSize(586, 44);
        _nsTextField1.setLocation(14, -12);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField3.setSize(20, 17);
        _nsTextField3.setLocation(-7, 31);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsTextField4.setSize(20, 17);
        _nsTextField4.setLocation(595, 31);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField4);
        _nsMatrix3.setSize(52, 159);
        _nsMatrix3.setLocation(506, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix3);
        _nsButton1.setSize(120, 28);
        _nsButton1.setLocation(481, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _popup0.setSize(163, 26);
        _popup0.setLocation(15, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsMatrix0.setSize(121, 163);
        _nsMatrix0.setLocation(382, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsMatrix1.setSize(225, 158);
        _nsMatrix1.setLocation(11, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix1);
        _popup2.setSize(106, 26);
        _popup2.setLocation(289, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup2, EOViewLayout.MinYMargin);
        _nsView0.add(_popup2);
        _nsMatrix4.setSize(91, 164);
        _nsMatrix4.setLocation(288, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix4);
        _nsMatrix2.setSize(46, 164);
        _nsMatrix2.setLocation(239, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix2);
        _nsMatrix5.setSize(41, 55);
        _nsMatrix5.setLocation(561, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix5, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix5);
        _nsButton0.setSize(40, 79);
        _nsButton0.setLocation(561, 162);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _popup1.setSize(95, 26);
        _popup1.setLocation(185, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView0.add(_popup1);
        _nsTextField5.setSize(80, 27);
        _nsTextField5.setLocation(400, 51);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField5);
        _nsView0.setSize(612, 252);
        _eoFrame0.setTitle("GeekCalc");
        _eoFrame0.setLocation(84, 443);
        _eoFrame0.setSize(612, 252);
    }
}
